# Generated by Django 4.2.11 on 2024-04-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('legal_entity', models.CharField(max_length=250)),
                ('subordination', models.CharField(max_length=250)),
                ('website', models.URLField()),
                ('inn', models.CharField(max_length=10)),
            ],
        ),
    ]
